version: '3.7'

services:

  mongo:
    image: mongo:latest
    restart: always
    container_name: my-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: carlos
      MONGO_INITDB_ROOT_PASSWORD: a1b2c3d4
    ports:
      - 27017:27017
    volumes:
      - ./data_mongo:/data/db
      
volumes:
  mongodb_data_container: